cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.panier_detail, name='panier_detail'),
    path('ajouter/<int:id_produit>/', views.ajouter_produit,
         name='ajouter_produit'),
    path('ajouter-un/<int:id_produit>/', views.ajouter_produit_direct,
         name='ajouter-un'),
    path('retirer/<int:id_produit>/', views.retirer_produit,
         name='retirer_produit'),
    path('maj/<int:id_produit>/', views.maj_quantite,
         name='maj_quantite')
]

myshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('panier/', include('cart.urls', namespace='cart')),
    path('compte/', include('account.urls', namespace='account')),
    path('commande/', include('orders.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('accounts/', include('allauth.urls')),
    path('', include('shop.urls', namespace='shop')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('produits/', views.produit_list,
         name='produit_list'),
    path('marques/', views.marque_list,
         name='marque_list'),
    path('categories/', views.categorie_list,
         name='categorie_list'),
    path('marques/<slug:marque_slug>/', views.produit_list_marque,
         name='produit_list_marque'),
    path('categories/<slug:categorie_slug>/', views.produit_list_categorie,
         name='produit_list_categorie'),
    path('marques/<slug:marque_slug>/<slug:categorie_slug>/', views.produit_list_marque_categorie,
         name='produit_list_marque_categorie'),
    path('produits/<int:id>/<slug:slug>/', views.produit_detail,
         name='produit_detail'),
    path('recherche_avancee/', views.recherche_avancee,
         name='recherche_avancee'),
]

shop/models.py
from django.utils import timezone
from django.db import models
from django.urls import reverse


class Categorie(models.Model):
    nom = models.CharField(max_length=255)
    slug = models.SlugField(max_length=200, unique=True, null=True)
    image = models.ImageField(upload_to='images/categories/%Y/%m/%d', blank=True, null=True)

    class Meta:
        ordering = ['nom']
        indexes = [
            models.Index(fields=['nom']),
        ]
        verbose_name = 'categorie'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.nom

    def get_absolute_url(self):
        return reverse('shop:produit_list_categorie',
                       args=[self.slug])


class Marque(models.Model):
    nom = models.CharField(max_length=255)
    slug = models.SlugField(max_length=200, unique=True, null=True)
    categorie = models.ManyToManyField(Categorie, through="Produit")
    image = models.ImageField(upload_to='images/marques/%Y/%m/%d', blank=True, null=True)

    class Meta:
        ordering = ['nom']
        indexes = [
            models.Index(fields=['nom']),
        ]
        verbose_name = 'marque'
        verbose_name_plural = 'marques'

    def __str__(self):
        return self.nom

    def get_absolute_url(self):
        return reverse('shop:produit_list_marque',
                       args=[self.slug])


class Promotion(models.Model):
    nom = models.CharField(max_length=255)
    slug = models.SlugField(max_length=200, null=True)
    taux_de_reduction = models.DecimalField(max_digits=5, decimal_places=2, null=True)
    ajouter = models.DateTimeField(default=timezone.now)
    modifier = models.DateTimeField(default=timezone.now)

    class Meta:
        ordering = ['modifier']
        indexes = [
            models.Index(fields=['nom']),
        ]

    def __str__(self):
        return self.nom


class Produit(models.Model):
    nom = models.CharField(max_length=255)
    slug = models.SlugField(max_length=200, null=True)
    description = models.JSONField()
    disponible = models.BooleanField(default=True)
    prix = models.DecimalField(max_digits=10, decimal_places=2)
    categorie = models.ForeignKey(Categorie, on_delete=models.CASCADE)
    marque = models.ForeignKey(Marque, on_delete=models.CASCADE)
    promotion = models.ForeignKey(Promotion, on_delete=models.SET_NULL, null=True, blank=True)
    image = models.ImageField(upload_to='images/produits/%Y/%m/%d/', null=True)
    ajouter = models.DateTimeField(default=timezone.now)
    modifier = models.DateTimeField(default=timezone.now)

    class Meta:
        ordering = ['modifier']
        indexes = [
            models.Index(fields=['id', 'slug']),
            models.Index(fields=['nom']),
            models.Index(fields=['-ajouter']),
        ]

    def __str__(self):
        return self.nom

    def get_absolute_url(self):
        return reverse('shop:produit_detail',
                       args=[self.id, self.slug])

    def prix_promotionnel(self):
        prix_reduit = self.prix * (1 - self.promotion.taux_de_reduction / 100)
        self.prix = prix_reduit
        return self.prix

    def is_active(self):
        return self.ajouter <= timezone.now() <= self.modifier


class Promo(models.Model):
    promotion = models.ForeignKey(Promotion, on_delete=models.SET_NULL, null=True, blank=True)
    produit = models.ForeignKey(Produit, on_delete=models.SET_NULL, null=True, blank=True)
    date_debut = models.DateTimeField(null=True)
    date_fin = models.DateTimeField(null=True)

    class Meta:
        ordering = ['date_fin']

    def __str__(self):
        return f"{self.promotion} - {self.produit}"

    def is_active(self):
        return self.date_debut <= timezone.now() <= self.date_fin if self.date_debut and self.date_fin else False

cart/forms.py
from django import forms


class FormulaireAjout(forms.Form):
    quantite = forms.IntegerField(
        initial=1,
        min_value=1,
        max_value=99,
        widget=forms.NumberInput(attrs={'class': 'ref-quantity-input'})
    )


class FormulaireSimple(forms.Form):
    def vide(self):
        return None


class FormulaireMajQuantite(forms.Form):
    quantite = forms.IntegerField(min_value=1,
                                  widget=forms.HiddenInput())

shop/forms.py
from django import forms


class FormulaireRA(forms.Form):
    mot_cle = forms.CharField(
        label='',
        max_length=50,
        required=False,
        widget=forms.TextInput(attrs={
            'class': 'form-control form-control-sm rounded-4',
            'placeholder': '🔍 Rechercher',
            'aria-label': 'Rechercher'  # Accessibilité pour les lecteurs d'écran
        })
    )

shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Marque, Categorie, Produit, Promo
import random
from cart.forms import FormulaireAjout
from .forms import FormulaireRA

m_slug_to_display = ['apple', 'samsung', 'asus', 'dell', 'sony']
marques_to_display = Marque.objects.filter(slug__in=m_slug_to_display)
c_slug_to_display = ['ordinateurs', 'smartphones', 'tablettes', 'gaming', 'cinema']
categories_to_display = Categorie.objects.filter(slug__in=c_slug_to_display)
formulaire_ajout = FormulaireAjout()
formulaire_recherche = FormulaireRA()


def promo_clearer():
    promos = Promo.objects.all()
    for promo in promos:
        if not promo.is_active():
            promo.promotion.delete()
            promo.delete()


def homepage(request):
    marques = Marque.objects.all()
    categories = Categorie.objects.all()
    promo_clearer()
    produits = Produit.objects.filter(disponible=True)
    produits_aleatoires = random.sample(list(produits), 12)
    marques_aleatoires = random.sample(list(marques), 9)
    return render(request,
                  'shop/index.html',
                  {'marques': marques,
                   'categories': categories,
                   'marques_to_display': marques_to_display,
                   'categories_to_display': categories_to_display,
                   'produits': produits_aleatoires,
                   'marques_aleatoires': marques_aleatoires,
                   'formulaire_ajout': formulaire_ajout,
                   'utilisateur': request.user,
                   'formulaire_recherche': formulaire_recherche})


def marque_list(request):
    marques = Marque.objects.all()
    categories = Categorie.objects.all()
    return render(request,
                  'shop/marque/marque_list.html',
                  {'marques': marques,
                   'categories': categories,
                   'marques_to_display': marques_to_display,
                   'categories_to_display': categories_to_display,
                   'utilisateur': request.user,
                   'formulaire_recherche': formulaire_recherche})


def categorie_list(request):
    categories = Categorie.objects.all()
    marques = Marque.objects.all()
    return render(request,
                  'shop/categorie/categorie_list.html',
                  {'categories': categories,
                   'marques': marques,
                   'marques_to_display': marques_to_display,
                   'categories_to_display': categories_to_display,
                   'utilisateur': request.user,
                   'formulaire_recherche': formulaire_recherche})


def produit_list(request, categorie_slug=None, marque_slug=None):
    categorie = None
    marque = None
    marques = Marque.objects.all()
    categories = Categorie.objects.all()
    promo_clearer()
    produits = Produit.objects.filter(disponible=True)
    if marque_slug and not categorie_slug:
        marque = get_object_or_404(Marque,
                                   slug=marque_slug)
        multi_categories = marque.categorie.all()
        produits = produits.filter(categorie__in=multi_categories,
                                   disponible=True)
    elif categorie_slug and not marque_slug:
        categorie = get_object_or_404(Categorie,
                                      slug=categorie_slug)
        produits = produits.filter(categorie=categorie)
    elif marque_slug and categorie_slug:
        marque = get_object_or_404(Marque,
                                   slug=marque_slug)
        multi_categories = marque.categorie.all()
        produits = produits.filter(categorie=categorie,
                                   categorie__in=multi_categories,
                                   disponible=True)
    return render(request,
                  'shop/produit/list.html',
                  {'categorie': categorie,
                   'categories': categories,
                   'marque': marque,
                   'marques': marques,
                   'produits': produits,
                   'marques_to_display': marques_to_display,
                   'categories_to_display': categories_to_display,
                   'formulaire_ajout': formulaire_ajout,
                   'utilisateur': request.user,
                   'formulaire_recherche': formulaire_recherche})


def produit_list_marque(request, marque_slug):
    marque = get_object_or_404(Marque, slug=marque_slug)
    marques = Marque.objects.all()
    categories = Categorie.objects.all()
    promo_clearer()
    produits = Produit.objects.filter(marque=marque, disponible=True)

    for produit in produits:
        promo = Promo.objects.filter(produit=produit).first()
        if promo and promo.is_active():
            produit.promotion = promo.promotion

    return render(request,
                  'shop/produit/list.html',
                  {'marque': marque,
                   'categories': categories,
                   'marques': marques,
                   'produits': produits,
                   'marques_to_display': marques_to_display,
                   'categories_to_display': categories_to_display,
                   'formulaire_ajout': formulaire_ajout,
                   'utilisateur': request.user,
                   'formulaire_recherche': formulaire_recherche})


def produit_list_categorie(request, categorie_slug):
    categorie = get_object_or_404(Categorie, slug=categorie_slug)
    marques = Marque.objects.all()
    categories = Categorie.objects.all()
    promo_clearer()
    produits = Produit.objects.filter(categorie=categorie, disponible=True)

    for produit in produits:
        promo = Promo.objects.filter(produit=produit).first()
        if promo and promo.is_active():
            produit.promotion = promo.promotion

    return render(request,
                  'shop/produit/list.html',
                  {'categorie': categorie,
                   'categories': categories,
                   'marques': marques,
                   'produits': produits,
                   'marques_to_display': marques_to_display,
                   'categories_to_display': categories_to_display,
                   'formulaire_ajout': formulaire_ajout,
                   'utilisateur': request.user,
                   'formulaire_recherche': formulaire_recherche})


def produit_list_marque_categorie(request, marque_slug, categorie_slug):
    marque = get_object_or_404(Marque, slug=marque_slug)
    categorie = get_object_or_404(Categorie, slug=categorie_slug)
    marques = Marque.objects.all()
    categories = Categorie.objects.all()
    promo_clearer()
    produits = Produit.objects.filter(marque=marque, categorie=categorie, disponible=True)

    for produit in produits:
        promo = Promo.objects.filter(produit=produit).first()
        if promo and promo.is_active():
            produit.promotion = promo.promotion

    return render(request,
                  'shop/produit/list.html',
                  {'marque': marque,
                   'categorie': categorie,
                   'categories': categories,
                   'marques': marques,
                   'produits': produits,
                   'marques_to_display': marques_to_display,
                   'categories_to_display': categories_to_display,
                   'formulaire_ajout': formulaire_ajout,
                   'utilisateur': request.user,
                   'formulaire_recherche': formulaire_recherche})


def produit_detail(request, id, slug):
    marques = Marque.objects.all()
    categories = Categorie.objects.all()
    produit = get_object_or_404(Produit,
                                id=id,
                                slug=slug,
                                disponible=True)
    return render(request,
                  'shop/produit/detail.html',
                  {'produit': produit,
                   'marques': marques,
                   'categories': categories,
                   'marques_to_display': marques_to_display,
                   'categories_to_display': categories_to_display,
                   'formulaire_ajout': formulaire_ajout,
                   'utilisateur': request.user,
                   'formulaire_recherche': formulaire_recherche})


def recherche_avancee(request):
    categories = Categorie.objects.all()
    marques = Marque.objects.all()

    if request.method == 'POST':
        formulaire = FormulaireRA(request.POST)
        if formulaire.is_valid():
            produits = Produit.objects.filter(disponible=True)

            mot_cle = formulaire.cleaned_data.get('mot_cle')

            if mot_cle:
                produits = produits.filter(nom__icontains=mot_cle)

            return render(request, 'shop/resultats.html', {
                'categories': categories,
                'marques': marques,
                'produits': produits,
                'marques_to_display': marques_to_display,
                'categories_to_display': categories_to_display,
                'formulaire_ajout': formulaire_ajout,
                'utilisateur': request.user,
                'formulaire_recherche': formulaire,
                'mot_cle': mot_cle
            })

    else:
        formulaire = FormulaireRA()

    return render(request, 'shop/index.html', {
        'categories': categories,
        'marques': marques,
        'marques_to_display': marques_to_display,
        'categories_to_display': categories_to_display,
        'formulaire_ajout': formulaire_ajout,
        'utilisateur': request.user,
        'formulaire_recherche': formulaire
    })

shop/templates/shop/produit/detail.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}{{ produit.nom }}{% endblock %}

{% block content %}
    <section class="py-5">
        <div class="container py-5">
            <div>
                <div class="reflow-product">
                    <div class="ref-media">
                        <div class="ref-preview shadow rounded-5">
                            <img class="ref-image active shadow" src="{{ produit.image.url }}" alt="{{ produit.nom }}" />
                        </div>
                        {% if produit.promotion %}
                            <div class="ref-promo-badge">{{ produit.promotion.taux_de_reduction }}</div>
                        {% endif %}
                    </div>
                    <div class="ref-product-data">
                        <h2 class="ref-name">{{ produit.nom }}</h2>
                        <div class="ref-rating ">
                            {% for _ in "12345" %}
                                <span class="star">&#9733;</span>
                            {% endfor %}
                        </div>
                        <div class="ref-categories">
                            <a href="{{ produit.categorie.get_absolute_url }}">
                                <span class="ref-category">{{ produit.categorie.nom }}</span>
                            </a>
                        </div>
                        <strong class="ref-price ref-on-sale">
                            {% if produit.promotion %}
                                <s class="ref-original-price">{{ produit.prix }} f</s>{{ produit.prix_promotionnel }} f
                            {% else %}
                                {{ produit.prix }} f
                            {% endif %}
                        </strong>
                        <span>
                            <div class="reflow-add-to-cart ref-product-controls">
                                <div class="ref-variant">
                                    <label>
                                    </label>
                                </div>
                                <span>
                                    <form id="ajouterProduitPanierForm" action="{% url "cart:ajouter_produit" produit.id %}" method="post">
                                        {% csrf_token %}
                                        <div class="ref-quantity-widget shadow">
                                            <div id="decreaseButton" class="ref-decrease" onclick="decreaseQuantite()">
                                                <span></span>
                                            </div>
                                            <input type="text" value="1" id="id_quantite" name="quantite" class="ref-quantity-field ref-quantity-input" style="font-size: 17px">
                                            <div id="increaseButton" class="ref-increase" onclick="increaseQuantite()">
                                                <span></span>
                                            </div>
                                        </div>
                                    </form>
                                </span>
                                <a class="ref-button ajouter-au-panier-btn-produit shadow" data-produit-id="{{ produit.id }}" type="button" onclick="ajouterAuPan({{ produit.id }})">Ajouter au panier</a>
                                <div class="form-check form-switch">
                                    <span ></span>
                                    <label class="form-check-label" for="descriptionSwitch">Description</label>
                                    <input class="form-check-input shadow" type="checkbox" id="descriptionSwitch">
                                </div>
                                <div class="row mt-3">
                                    <div class="col">
                                        <div class="ref-categories shadow rounded-3 p-3" id="descriptionContent" style="display: none;">
                                            {% for key, value in produit.description.items %}
                                                <span style="color: dimgray"><b>{{ key }}:</b></span>
                                                <span class="ref-category float-end">{{ value }}</span><br>
                                            {% endfor %}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </span>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

shop/templates/shop/produit/list.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
    {% if marque %}{{ marque.nom }}{% elif categorie %}{{ categorie.nom }}{% else %} Produits {% endif %}
{% endblock %}

{% block content%}
    <section class="py-5">
        <!-- Start: Product -->
        <div class="container py-5">
            <div class="row mb-4 mb-lg-5">
                <div class="col-md-8 col-xl-6 text-center mx-auto">
                    <h2 class="fw-bold"></h2>
                    <!-- Placeholder for messages -->
                    <p class="text-black"></p>
                </div>
            </div>
            <div class="row mx-auto">
                <div class="col">
                    <div>
                        <div class="reflow-product-list ref-cards">
                            <div class="ref-products">
                                {% for produit in produits %}
                                    <div class="ref-product shadow rounded">
                                        <a class="ref-product" href="{{ produit.get_absolute_url }}">
                                            <div class="ref-media">
                                                <img class="ref-image rounded" src="{{ produit.image.url }}" alt="{{ produit.slug }}" loading="lazy" />
                                                <!-- reduction banniere -->
                                                {% if produit.promotion %}
                                                    <div class="ref-promo-badge"><s>{{ produit.promotion.taux_de_reduction}} %</s></div>
                                                {% endif %}
                                            </div>
                                            <div class="ref-product-data p-2">
                                                <div class="ref-product-info">
                                                    <h5 class="ref-name">{{ produit.nom }}</h5>
                                                    <div class="ref-rating ">
                                                        {% for _ in "12345" %}
                                                            <span class="star">&#9733;</span>
                                                        {% endfor %}
                                                    </div>
                                                    <p class="ref-excerpt">
                                                        {{ produit.description.Résolution|default:"N/A" }}
                                                    </p>
                                                </div>
                                                {% if produit.promotion %}
                                                    <strong class="ref-price ref-on-sale">
                                                        <s class="ref-original-price">{{ produit.prix }} f</s>{{ produit.prix_promotionnel }} f
                                                    </strong>
                                                {% else %}
                                                    <strong class="ref-price">
                                                        {{ produit.prix }} f
                                                    </strong>
                                                {% endif %}
                                            </div>
                                        </a>
                                        <div class="ref-addons">
                                            <div class="d-flex justify-content-around pb-2">
                                                <span>
                                                    <form id="ajouterUnAuPanierForm-{{ produit.id }}" action="{% url "cart:ajouter-un" produit.id %}" method="post">
                                                        {% csrf_token %}
                                                    </form>
                                                </span>
                                                <a id="ajouterUnAuPanierBtn-{{ produit.id }}" class="ref-button shadow ajouter-un-au-panier-btn shadow-lg" data-produit-id="{{ produit.id }}" type="submit">Ajouter au panier</a>
                                            </div>
                                        </div>
                                    </div>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                    <div class="ref-product-preview">
                        <div class="ref-product-preview-header">
                            <div class="ref-title"></div>
                            <div class="ref-close-button">×</div>
                        </div>
                        <div class="ref-product-preview-content"></div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}