account/urls.py
from django.urls import path
from . import views

app_name = 'account'

urlpatterns = [
    path('connexion/', views.connexion, name='connexion'),
    path('deconnexion/', views.deconnexion, name='deconnexion'),
    path('mdp_reinit_dem/', views.mdp_reinit_dem, name='mdp_reinit_dem'),
    path('mdp-reinit/<str:uid>/<str:token>/', views.mdp_reinit, name='mdp_reinit'),
    path('mdp_change/', views.mdp_change, name='mdp_change'),
    path('compte_creation/', views.compte_creation, name='compte_creation'),
    path('activation/<str:uidb64>/<str:token>/', views.compte_activation, name='compte_activation'),
    path('activation_reussi/', views.activation_reussi, name='activation_reussi'),
    path('profile_edit/', views.profile_edit, name='profile_edit'),
]

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.panier_detail, name='panier_detail'),
    path('ajouter/<int:id_produit>/', views.ajouter_produit,
         name='ajouter_produit'),
    path('ajouter-un/<int:id_produit>/', views.ajouter_produit_direct,
         name='ajouter-un'),
    path('retirer/<int:id_produit>/', views.retirer_produit,
         name='retirer_produit'),
    path('maj/<int:id_produit>/', views.maj_quantite,
         name='maj_quantite')
]

myshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('panier/', include('cart.urls', namespace='cart')),
    path('compte/', include('account.urls', namespace='account')),
    path('commande/', include('orders.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('accounts/', include('allauth.urls')),
    path('', include('shop.urls', namespace='shop')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('creer_commande/', views.creer_commande, name='creer_commande'),
    path('admin/commande/<int:id_commande>/pdf/', views.admin_commande_pdf, name='admin_commande_pdf'),
    path('commandes/', views.liste_commandes, name='liste_commandes'),
    path('commandes/<int:id>/', views.commande_detail, name='commande_detail'),
    path('commandes/<int:id_commande>/pdf/', views.commande_pdf, name='commande_pdf'),
]

payment/urls.py
from django.urls import path
from . import views
from . import webhooks

app_name = 'payment'

urlpatterns = [
    path('processus_de_paiement/', views.processus_de_paiement, name='processus_de_paiement'),
    path('paiement_unique/<int:id_commande>', views.paiement_unique, name='paiement_unique'),
    path('paiement_reussi/', views.paiement_reussi, name='paiement_reussi'),
    path('paiement_annuler/', views.paiement_annuler, name='paiement_annuler'),
    path('webhook/', webhooks.stripe_webhook, name='stripe-webhook')
]

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('produits/', views.produit_list,
         name='produit_list'),
    path('marques/', views.marque_list,
         name='marque_list'),
    path('categories/', views.categorie_list,
         name='categorie_list'),
    path('marques/<slug:marque_slug>/', views.produit_list_marque,
         name='produit_list_marque'),
    path('categories/<slug:categorie_slug>/', views.produit_list_categorie,
         name='produit_list_categorie'),
    path('marques/<slug:marque_slug>/<slug:categorie_slug>/', views.produit_list_marque_categorie,
         name='produit_list_marque_categorie'),
    path('produits/<int:id>/<slug:slug>/', views.produit_detail,
         name='produit_detail'),
    path('recherche_avancee/', views.recherche_avancee,
         name='recherche_avancee'),
]

orders/models.py
from django.db import models
from shop.models import Produit
from account.models import Utilisateur
from django.conf import settings


# Create your models here.


class Commande(models.Model):
    utilisateur = models.ForeignKey(Utilisateur, on_delete=models.CASCADE)
    creer = models.DateTimeField(auto_now_add=True)
    modifier = models.DateTimeField(auto_now_add=True)
    payer = models.BooleanField(default=False)
    stripe_id = models.CharField(max_length=250, blank=True)

    def nom(self):
        return f'{self.utilisateur.nom}'

    def prenom(self):
        return f'{self.utilisateur.prenom}'

    def email(self):
        return f'{self.utilisateur.email}'

    def adresse(self):
        return f'{self.utilisateur.adresse}'

    def code_postal(self):
        return f'{self.utilisateur.code_postal}'

    def ville(self):
        return f'{self.utilisateur.ville}'

    def telephone(self):
        return f'{self.utilisateur.telephone}'

    def get_stripe_url(self):
        if not self.stripe_id:
            return ''
        if '_test_' in settings.STRIPE_SECRET_KEY:

            path = '/test/'
        else:

            path = '/'
        return f'https://dashboard.stripe.com{path}payments/{self.stripe_id}'

    def generer_numero_commande(self):
        partie_fixe = hex(self.id)[2:].zfill(4)

        date_partie_variable = self.creer.strftime('%Y%m%d') if self.creer else '00000000'

        if self.utilisateur:
            prenom_partie_variable = self.utilisateur.prenom[0].upper()
            nom_partie_variable = self.utilisateur.nom[-1].upper()
        else:
            prenom_partie_variable = 'X'
            nom_partie_variable = 'X'

        numero_commande_masque = f'CMD-{partie_fixe}-{date_partie_variable}-{prenom_partie_variable}{nom_partie_variable}'

        return numero_commande_masque

    class Meta:
        ordering = ['-creer']
        indexes = [models.Index(fields=['-creer'])]

    def __str__(self):
        return f'{self.generer_numero_commande()}'

    def cout_total(self):
        total = f"{sum(item.cout() for item in self.items.all()):,.2f}"
        return float(total.replace(',', ''))

    def frais(self):
        x = 0.01
        frais = f"{self.cout_total() * x:,.2f}"
        return float(frais.replace(',', ''))



class CommandeItem(models.Model):
    commande = models.ForeignKey(Commande,
                                 related_name='items', on_delete=models.CASCADE)
    produit = models.ForeignKey(Produit,
                                related_name='order_items', on_delete=models.CASCADE)
    quantite = models.PositiveIntegerField(default=1)
    prix = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return f'{self.quantite} x {self.produit.nom}'

    def cout(self):
        return self.quantite * self.prix

    def ct(self):
        return self.quantite * self.prix

orders/forms.py
from django import forms
from .models import Commande


class FormulaireDeCC(forms.ModelForm):
    email = forms.EmailField(label='Email', required=True, widget=forms.EmailInput(attrs={
        'class': 'form-control rounded-3 shadow', 'placeholder': 'Email'}))
    nom = forms.CharField(label='Nom', max_length=50, required=True, widget=forms.TextInput(attrs={
        'class': 'form-control rounded-3 shadow', 'placeholder': 'nom et prenom'}))
    adresse = forms.CharField(label='Adresse', max_length=50, required=False, widget=forms.Textarea(attrs={
        'class': 'form-control rounded-3 shadow', 'placeholder': 'adresse', 'rows': 2}))
    telephone = forms.CharField(label='Telephone', max_length=12, required=True, widget=forms.TextInput(attrs={
        'class': 'form-control rounded-3 shadow', 'placeholder': 'Telephone'}))
    code_postal = forms.CharField(label='Code postal', max_length=30, required=False, widget=forms.TextInput(attrs={
        'class': 'form-control rounded-3 shadow', 'placeholder': 'code postal'}))
    ville = forms.CharField(label='Ville', max_length=30, required=True, widget=forms.TextInput(attrs={
        'class': 'form-control rounded-3 shadow', 'placeholder': 'ville'}))

    class Meta:
        model = Commande
        exclude = ['utilisateur']  # Exclude the utilisateur field, as it's a ForeignKey relationship

orders/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from cart.cart import Panier
from django.template.loader import render_to_string
from .forms import FormulaireDeCC
from .models import CommandeItem
from django.conf import settings
from django.http import HttpResponse
from shop.models import Marque, Categorie
from .models import Commande, CommandeItem
from .forms import FormulaireDeCC
from .tasks import commande_passer
from django.urls import reverse
import weasyprint
from django.contrib.admin.views.decorators import staff_member_required
from shop.forms import FormulaireRA

# Create your views here.


marques = Marque.objects.all()
categories = Categorie.objects.all()
m_slug_to_display = ['apple', 'samsung', 'asus', 'dell', 'sony']
marques_to_display = Marque.objects.filter(slug__in=m_slug_to_display)
c_slug_to_display = ['ordinateurs', 'smartphones', 'tablettes', 'gaming', 'cinema']
categories_to_display = Categorie.objects.filter(slug__in=c_slug_to_display)
formulaire_recherche = FormulaireRA()


def creer_commande(request):
    panier = Panier(request)
    total = panier.get_prix_total()
    utilisateur = request.user
    initial_data = {
        'email': utilisateur.email,
        'nom': f"{utilisateur.nom} {utilisateur.prenom}",
        'adresse': utilisateur.adresse,
        'telephone': utilisateur.telephone,
        'code_postal': utilisateur.code_postal,
        'ville': utilisateur.ville
    }

    if request.method == 'POST':
        formulaire = FormulaireDeCC(request.POST)

        if formulaire.is_valid():
            commande = formulaire.save(commit=False)
            commande.utilisateur = utilisateur
            commande.save()

            for item in panier:
                CommandeItem.objects.create(
                    commande=commande,
                    produit=item['produit'],
                    prix=item['prix'],
                    quantite=item['quantite']
                )

            panier.effacer()

            commande_passer.delay(commande.id)

            request.session['id_commande'] = commande.id

            return redirect(reverse('payment:processus_de_paiement'))

    else:
        formulaire = FormulaireDeCC(initial=initial_data)

    return render(request, 'orders/cr_commande.html', {
        'panier': panier,
        'formulaire': formulaire,
        'utilisateur': request.user,
        'categories': categories,
        'marques': marques,
        'marques_to_display': marques_to_display,
        'categories_to_display': categories_to_display,
        'formulaire_recherche': formulaire_recherche,
    })


@staff_member_required
def admin_commande_pdf(request, id_commande):
    commande = get_object_or_404(Commande, id=id_commande)
    html = render_to_string('orders/pdf.html',
                            {'commande': commande})
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = f'filename=commande_{commande.generer_numero_commande()}.pdf'
    weasyprint.HTML(string=html).write_pdf(response,
                                           stylesheets=[weasyprint.CSS(
                                               settings.STATIC_ROOT / 'bootstrap/css/bootstrap.min.css')])
    return response


@login_required
def commande_pdf(request, id_commande):
    commande = get_object_or_404(Commande, id=id_commande)

    if commande.utilisateur != request.user:
        return HttpResponse("Unauthorized", status=401)

    html = render_to_string('orders/pdf.html', {'commande': commande})
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = f'filename=commande_{commande.generer_numero_commande()}.pdf'
    weasyprint.HTML(string=html).write_pdf(response,
                                           stylesheets=[weasyprint.CSS(
                                               settings.STATIC_ROOT / 'bootstrap/css/bootstrap.min.css')])
    return response


@login_required
def liste_commandes(request):
    user = request.user
    status = request.GET.get('status', '')

    commandes = Commande.objects.filter(utilisateur=user)
    if status == 'paid':
        commandes = commandes.filter(payer=True)
    elif status == 'not-paid':
        commandes = commandes.filter(payer=False)

    return render(request, 'orders/liste_commandes.html', {
        'commandes': commandes,
        'categories': categories,
        'marques': marques,
        'utilisateur': request.user,
        'marques_to_display': marques_to_display,
        'categories_to_display': categories_to_display,
        'formulaire_recherche': formulaire_recherche,
    })


def commande_detail(request, id):
    commande = get_object_or_404(Commande, id=id)
    return render(request, 'orders/commande_detail.html', {'commande': commande,
                                                           'utilisateur': request.user,
                                                           'categories': categories,
                                                            'marques': marques,
                                                            'marques_to_display': marques_to_display,
                                                            'categories_to_display': categories_to_display,
                                                            'formulaire_recherche': formulaire_recherche,
                                                           })

orders/templates/orders/cr_commande.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}
{% endblock %}

{% block content %}
    <section class="py-5">
        <div class="container py-5">
            <div class="row mx-auto">
                <div class="col">
                    <div data-reflow-type="shopping-cart">
                        <div class="reflow-shopping-cart" style="display: block;">
                            <div class="ref-loading-overlay"></div>
                            <div class="ref-message" style="display: none;"></div>
                            <div class="ref-checkout">
                                <div class="ref-checkout-content">
                                    <form id="creerCommandeForm" class="ref-details" style="display: block;" action="{% url "orders:creer_commande" %}" method="post">
                                        {% csrf_token %}
                                        <div class="ref-back">
                                            <a href="{% url "cart:panier_detail" %}">
                                                ← retour au panier
                                            </a>
                                        </div>
                                        <div class="ref-heading">Infos du client</div>
                                        <div class="text-center ref-auth-button-holder" style="display: block;">
                                            <div class="ref-auth-button" data-reflow-type="auth-button">
                                                <div class="reflow-auth-button">
                                                    {% if utilisateur.is_authenticated %}
                                                        <div class="ref-auth-button-signed" style="display: block;">
                                                            <a class="ref-profile-info" href="{% url "account:profile_edit" %}">
                                                                {% if utilisateur.image %}
                                                                    <img class="ref-profile-photo rounded-circle" src="{{ utilisateur.image.url }}" width="45" height="45">
                                                                    <span class="ref-profile-name" style="color: darkgrey">{{ utilisateur.prenom }} {{ utilisateur.nom }}</span>
                                                                {% else %}
                                                                    <svg class="bi bi-person" xmlns="http://www.w3.org/2000/svg" width="45" height="45" fill="currentColor" viewBox="0 0 16 16">
                                                                        <path d="M8 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6Zm2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0Zm4 8c0 1-1 1-1 1H3s-1 0-1-1 1-4 6-4 6 3 6 4Zm-1-.004c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10Z"></path>
                                                                    </svg>
                                                                {% endif %}
                                                            </a>
                                                        </div>
                                                    {% else %}
                                                        <div class="ref-auth-button-guest">
                                                            <div class="ref-button ref-sign-in">
                                                                <a href="{% url "account:connexion" %}">
                                                                    Se Connecter
                                                                </a>
                                                            </div>
                                                            <div class="ref-register">
                                                                Vous ne possedez pas un compte?
                                                                <span class="text-primary">
                                                                    <a href="{% url "account:compte_creation" %}">Creez-en!</a>
                                                                    <span>
                                                                    </span>
                                                                </span>
                                                            </div>
                                                        </div>
                                                    {% endif %}
                                                </div>
                                            </div>
                                        </div>
                                        <label>
                                            {{ formulaire.email }}
                                        </label>
                                        <label class="ref-phone-input">
                                            {{ formulaire.telephone }}
                                            <div class="ref-validation-error">
                                            </div>
                                        </label>
                                        <div class="ref-heading ref-heading-delivery" style="display: block;">Livraison</div>
                                        <div class="ref-delivery-card bg-light shadow" style="display: block;">
                                            <div class="ref-tab ref-shipping-tab open" data-ref-delivery="shipping" style="display: block;">
                                                <fieldset class="ref-tab-content">
                                                    <div class="ref-shipping-address-holder">
                                                        <div class="ref-address-widget">
                                                            <label>
                                                                <span>Nom</span>
                                                                {{ formulaire.nom }}
                                                            </label>
                                                            <label>
                                                                <span>Adresse</span>
                                                                {{ formulaire.adresse }}
                                                            </label>
                                                            <label>
                                                                <span>Ville</span>
                                                                {{ formulaire.ville }}
                                                            </label>
                                                        </div>
                                                        <div class="ref-row ref-row-region">
                                                                <label>
                                                                    <span>Code Postal</span>
                                                                    {{ formulaire.code_postal }}
                                                                </label>
                                                            </div>
                                                    </div>
                                                    <div class="ref-auth-save-address" style="display: block;">
                                                        <label>
                                                            <input type="checkbox" name="auth-save-address" checked />
                                                            <span>Enregistrer mon adresse pour les futurs achats</span>
                                                        </label>
                                                    </div>
                                                </fieldset>
                                            </div>
                                        </div>
                                        <div>
                                            <div class="ref-standard-payment-buttons">
                                                <div id="creer_commande_btn" class="ref-button ref-payment-button ref-payment-card button-demo-payment shadow"  data-method="stripe">Commander</div>
                                            </div>
                                        </div>
                                    </form>
                                    <div class="ref-links">
                                    </div>
                                </div>
                                <div class="ref-checkout-summary shadow" style="background-color: #f5f6f8 !important">
                                    <div class="ref-heading">Details de la commande</div>
                                    <div class="ref-products">
                                        {% for item in panier %}
                                            <div class="ref-product">
                                                <div class="ref-product-col">
                                                    <a href="{{ item.produit.get_absolute_url }}">
                                                        <img class="ref-product-photo" src="{{ item.produit.image.url }}" alt="{{ item.produit.slug }}"/>
                                                    </a>
                                                    <div>
                                                        <a href="{{ item.produit.get_absolute_url }}">
                                                            <div class="ref-product-name">{{ item.produit.nom }}</div>
                                                        </a>
                                                        <div class="ref-product-secondary">{{ item.produit.prix }} x {{ item.quantite }}</div>
                                                    </div>
                                                </div>
                                                <div>
                                                    <div class="ref-product-total">{{ item.prix_total }}</div>
                                                </div>
                                            </div>
                                        {% endfor %}
                                    </div>
                                    <hr style="display: block;" />
                                    <div class="ref-totals">
                                        <div class="ref-subtotal">
                                            <div class="ref-row">
                                                <span>Somme totale</span>
                                                <span>{{ panier.get_prix_total }}</span>
                                            </div>
                                        </div>
                                        <div class="ref-shipping" style="display: block;">
                                            <div class="ref-row">
                                                <span>Livraison (Dans tout le pays)</span>
                                                <span>{{ panier.frais }}</span>
                                            </div>
                                        </div>
                                    </div>
                                    <hr />
                                    <div class="ref-total">
                                        <div class="ref-row">
                                            <span>Total</span>
                                            <span>{{ panier.get_prix_total|add:panier.frais }}</span>
                                        </div>
                                        <div class="ref-total-note">Tous les prix sont en francs cfa.</div>
                                    </div>
                                </div>
                                <div class="ref-summary-toggle ref-field-collapsible">
                                    <span class="ref-field-toggle">
                                        <span class="ref-field-toggle-title">Details</span>
                                        <span class="ref-summary-total">{{ panier.get_prix_total|add:panier.frais }} f</span>
                                    </span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

orders/templates/orders/liste_commandes.html
{% extends "shop/index.html" %}
{% load static %}

{% block title %}
    Commandes
{% endblock %}

{% block content %}
    <section class="py-3">
        <div class="px-4 py-3">
            <div class="row mx-auto">
                <div class="col">
                    <div class="ref-cart">
                        <div class="d-flex justify-content-between align-items-center mb-4">
                            <h2>Historique de Commandes</h2>
                            <!-- Filtres -->
                            <form id="filter-form" method="get" class="form-inline">
                                <div class="form-group mb-3">
                                    <select name="status" id="status" class="form-control form-control-sm" onchange="document.getElementById('filter-form').submit();">
                                        <option value="">Tout</option>
                                        <option value="paid" {% if request.GET.status == 'paid' %}selected{% endif %}>Payé</option>
                                        <option value="not-paid" {% if request.GET.status == 'not-paid' %}selected{% endif %}>En attente</option>
                                    </select>
                                </div>
                            </form>
                        </div>
                        {% if commandes %}
                            <!-- En-têtes -->
                            <div class="d-flex justify-content-between border-bottom pb-2">
                                <div class="text-center mb-4" style="width: 20%;">Numéro de Commande</div>
                                <div class="text-center mb-4" style="width: 20%;">Date</div>
                                <div class="text-center mb-4" style="width: 20%;">Status</div>
                                <div class="text-center mb-4" style="width: 20%;">Montant</div>
                                <div class="text-center mb-4" style="width: 20%;">Action</div>
                            </div>
                            <!-- Contenu -->
                            {% for commande in commandes %}
                                <div class="d-flex justify-content-between border-bottom py-2">
                                    <div class="text-center" style="width: 20%;">{{ commande.generer_numero_commande }}</div>
                                    <div class="text-center" style="width: 20%;">{{ commande.creer|date:"F d, Y H:i" }}</div>
                                    <div class="text-center" style="width: 20%;">
                                        {% if commande.payer %}
                                            <span class="badge badge-success" style="background-color:rgb(32, 204, 32)">Payé</span>
                                        {% else %}
                                            <span class="badge badge-warning" style="background-color: rgb(169, 169, 169)">En attente</span>
                                        {% endif %}
                                    </div>
                                    <div class="text-center" style="width: 20%;">{{ commande.cout_total|floatformat:2 }} f</div>
                                    <div class="text-center" style="width: 20%;" class="text-center">
                                        <a href="{% url 'orders:commande_detail' id=commande.id %}" class="btn btn-primary btn-sm me-1">Détails</a>
                                        <a href="{% url 'orders:commande_pdf' id_commande=commande.id %}" class="btn btn-primary btn-sm mx-1">Télécharger</a>
                                    </div>
                                </div>
                            {% endfor %}
                        {% else %}
                            <div class="text-center py-3">Aucune commande trouvée dans votre historique.</div>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}